export interface NeighborhoodData {
  slug: string
  name: string
  citySlug: string
  cityName: string
  metaTitle: string
  metaDescription: string
  h1: string
  intro: string
  propertyTypes: string[]
  housingNote: string
  testimonial: { quote: string; name: string; location: string }
  faqs: Array<{ question: string; answer: string }>
}

export const NEIGHBORHOODS: NeighborhoodData[] = [
  { slug:'georgetown',name:'Georgetown',citySlug:'washington-dc',cityName:'Washington, DC',metaTitle:'House Cleaning in Georgetown, DC | RenewShine',metaDescription:'Premium residential cleaning in Georgetown, DC. Photo-reviewed quotes for historic row houses, Federal townhomes, and luxury condos. Confirmed price before you pay.',h1:'House Cleaning in Georgetown, DC',intro:"Georgetown's historic row houses, Federal-style townhomes, and luxury condos require cleaning professionals who understand the architecture — and the price. RenewShine reviews photos of your actual space before confirming any quote, so you're never surprised when we arrive.",propertyTypes:['Historic row houses','Federal townhomes','Luxury condos','Canal-side apartments'],housingNote:"Georgetown homes range from 18th-century Federal row houses to modern luxury condos — every property is reviewed individually before we quote.",testimonial:{quote:"Finally found a service that understands Georgetown homes aren't like a standard 2-bedroom. They reviewed my photos and gave me an exact price. No surprises at all.",name:'Caroline M.',location:'Georgetown, DC'},faqs:[{question:'How much does house cleaning cost in Georgetown, DC?',answer:'Georgetown homes typically range from $200–$500 depending on size, condition, and service type. We review photos of your space and confirm an exact price before you pay anything.'},{question:'Do you clean historic row houses in Georgetown?',answer:"Yes. Our photo review process is built for properties like Georgetown row houses, where condition and layout vary significantly from the bedroom count. We account for actual scope before confirming any price."},{question:'Do you offer move-out cleaning in Georgetown, DC?',answer:'Yes. Move-out cleaning is one of our most requested services in Georgetown. Every move-out clean includes inside the oven, inside the refrigerator, inside all cabinets, and spot-cleaned walls — all quoted after photo review.'},{question:'Do I need to be home during the cleaning in Georgetown?',answer:'No. Most Georgetown clients provide a lockbox code or key and return to a fully cleaned home. Include your building access details in the booking notes.'}]},
  { slug:'capitol-hill',name:'Capitol Hill',citySlug:'washington-dc',cityName:'Washington, DC',metaTitle:'House Cleaning in Capitol Hill, DC | RenewShine',metaDescription:'Professional cleaning for Capitol Hill row houses, condos, and apartments. Photo-reviewed pricing — confirmed before you pay. Serving SE and NE DC.',h1:'House Cleaning in Capitol Hill, DC',intro:"Capitol Hill's classic DC row houses and converted apartments are some of the most character-rich homes in the city — and some of the most variable in condition. RenewShine reviews your photos before confirming any price, so there are no surprises when we arrive.",propertyTypes:['Victorian row houses','Condos','Converted apartments','Townhomes'],housingNote:'Capitol Hill has a strong mix of Victorian and Edwardian row houses, basement apartments, and newer condo conversions — all priced individually after photo review.',testimonial:{quote:"I was nervous about hiring a new service for my row house. They asked for photos first, reviewed them, and gave me a real confirmed price. That alone made me trust them.",name:'Marcus T.',location:'Capitol Hill, DC'},faqs:[{question:'How much does house cleaning cost in Capitol Hill, DC?',answer:'Capitol Hill homes typically range from $200–$480 depending on size, condition, and service type. We confirm your exact price after reviewing photos — before you pay anything.'},{question:'Do you clean row houses and condos on Capitol Hill?',answer:'Yes — Victorian row houses, condo conversions, basement apartments, and townhomes throughout Capitol Hill and the surrounding SE and NE neighborhoods.'},{question:'What does a deep clean include for a Capitol Hill row house?',answer:'Everything in Standard Clean plus inside oven, inside refrigerator, hard water stain removal, under and behind accessible furniture, vents, cobwebs, and wet-wiped baseboards and light switches.'},{question:'Do you handle building access for Capitol Hill apartments?',answer:'Yes. Include your key fob code, lockbox details, or concierge instructions in the booking notes. Most clients are not home during the clean.'}]},
  { slug:'clarendon',name:'Clarendon',citySlug:'arlington-va',cityName:'Arlington, VA',metaTitle:'House Cleaning in Clarendon, Arlington VA | RenewShine',metaDescription:'Premium house cleaning in Clarendon, Arlington. Photo-reviewed pricing for condos, apartments, and townhomes. Serving the Clarendon-Courthouse corridor.',h1:'House Cleaning in Clarendon, Arlington VA',intro:"Clarendon's dense mix of high-rise condos, walkup apartments, and new-build townhomes makes it one of Arlington's most active neighborhoods. RenewShine serves the full Clarendon-Courthouse corridor with photo-reviewed quotes — confirmed before you pay a cent.",propertyTypes:['High-rise condos','Walkup apartments','Townhomes','New-build units'],housingNote:'Clarendon has a high concentration of condo buildings and luxury apartments along the Orange Line corridor — all handled through our review-based quoting process.',testimonial:{quote:"Super easy process for my Clarendon condo. Sent photos, got a confirmed price the same day, and the team showed up on time and did a great job.",name:'Danielle R.',location:'Clarendon, Arlington VA'},faqs:[{question:'How much does apartment cleaning cost in Clarendon, Arlington?',answer:'Most Clarendon apartments range from $200–$380 for standard cleaning. We review your photos and confirm an exact price before you pay — not an estimate that changes at the door.'},{question:'Do you clean high-rise condos in Clarendon?',answer:'Yes. We serve high-rise buildings, walkup apartments, and townhomes throughout the Clarendon-Courthouse corridor. Include your building access instructions in the booking notes.'},{question:'Do you offer recurring cleaning in Clarendon, Arlington?',answer:'Yes. Many Clarendon clients choose bi-weekly or monthly recurring plans. Recurring clients receive a custom discounted rate on Standard Cleans. Select your frequency during booking.'},{question:'Do I need to be home during the cleaning?',answer:'No. Most clients provide a lockbox code or key fob access and return to a fully cleaned home. Include your access details in the booking notes.'}]},
]
export function getNeighborhoodBySlug(citySlug: string, neighborhoodSlug: string){return NEIGHBORHOODS.find((n)=>n.citySlug===citySlug&&n.slug===neighborhoodSlug)}
export function getNeighborhoodsByCitySlug(citySlug: string){return NEIGHBORHOODS.filter((n)=>n.citySlug===citySlug)}
